---
version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
    
networks:
  front-tier:
  back-tier:
  
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus:/config
      - prometheus-data:/prometheus
    command:
      - "--web.enable-lifecycle"
      - "--config.file=/config/prometheus.yml"
    networks:
      - back-tier
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - back-tier
      - front-tier
    restart: unless-stopped
